// SEO helpers — keep all canonical URL + organisation + author entities in one place.

export const SITE = {
  url: "https://startupgrowthhacks.com",
  name: "Startup Growth Hacks",
  description:
    "The deepest indexed library of 464 hand-illustrated growth hacks for early-stage startups — every play covers acquisition, conversion, retention, monetisation, referral and AI GEO with the how, the example, and the gotcha.",
  author: "Jaisal Rathee",
};

export function canonical(path: string): string {
  if (!path.startsWith("/")) path = "/" + path;
  return `${SITE.url}${path === "/" ? "" : path}`;
}

// Default OG image generated by app/opengraph-image.tsx — explicitly applied to each page's metadata
// because per-page openGraph overrides root layout's (no auto-inherit of the image).
export const DEFAULT_OG_IMAGE = [
  {
    url: `${SITE.url}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: "Startup Growth Hacks — 464 hand-illustrated growth plays for 2026",
  },
];

// Reusable Organization entity referenced by every Article schema for AI engine citation trust.
export const ORG_SCHEMA = {
  "@type": "Organization",
  "@id": `${SITE.url}#organization`,
  name: SITE.name,
  url: SITE.url,
  description: SITE.description,
  founder: {
    "@type": "Person",
    name: "Jaisal Rathee",
    jobTitle: "Growth Advisor & Founder",
    url: `${SITE.url}/book`,
  },
  logo: {
    "@type": "ImageObject",
    url: `${SITE.url}/opengraph-image`,
    width: 1200,
    height: 630,
  },
  sameAs: [
    "https://github.com/jaisalrathee/startupgrowthhacks",
  ],
};

export const PERSON_SCHEMA = {
  "@type": "Person",
  "@id": `${SITE.url}#jaisal`,
  name: "Jaisal Rathee",
  jobTitle: "Growth Advisor",
  url: `${SITE.url}/book`,
  worksFor: { "@id": `${SITE.url}#organization` },
  knowsAbout: [
    "Conversion rate optimization",
    "Growth marketing",
    "SaaS growth",
    "Startup acquisition",
    "Pricing strategy",
    "User activation",
    "Customer retention",
    "AI search optimization",
    "Generative engine optimization",
  ],
};

export const WEBSITE_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE.url}#website`,
  url: SITE.url,
  name: SITE.name,
  description: SITE.description,
  publisher: { "@id": `${SITE.url}#organization` },
  potentialAction: {
    "@type": "SearchAction",
    target: { "@type": "EntryPoint", urlTemplate: `${SITE.url}/?q={search_term_string}` },
    "query-input": "required name=search_term_string",
  },
};

export function breadcrumb(items: Array<{ name: string; url: string }>) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: it.url,
    })),
  };
}
